### ISSUE TITLE
extend

### ISSUE THREAD

**Issue by marte-git** [davide-dascanio/Homework-XHTML-CSS#1]
provi ad aggiungere immagini nella pagine descrittive;
poi potrebbe definire un file header, da importare nelle pagine, contenente un embrione di quello che potrebbe diventare un menu'

in questo momento il menu' e' abbastanza ristretto ("Home") perche' da una pagina descrittiva si puo' solo tornare alla home.

Per le immagini, quando sono piu' di una, provi ad usare flex per ordinarle (google "flex css-trics" 

Poi risponda a questa issue cosi' verifico e la dichiaro chiusa, ok?

**Comment by davide-dascanio** [comment]
Salve professore, ho effettuato le correzioni da lei richieste.
Buona giornata.
